[tool.poetry]
name = "ocr-practice"
version = "0.1.0"
description = ""
authors = ["hachimada"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
easyocr = "^1.7.1"
opencv-python = "^4.8.1.78"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
